<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace User\V1;

if (false) {
    /**
     * This class is deprecated. Use User\V1\UidReq\Type instead.
     * @deprecated
     */
    class UidReq_Type {}
}
class_exists(UidReq\Type::class);
@trigger_error('User\V1\UidReq_Type is deprecated and will be removed in the next major release. Use User\V1\UidReq\Type instead', E_USER_DEPRECATED);

