<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace User\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.v1.UserAllRes</code>
 */
class UserAllRes extends \Google\Protobuf\Internal\Message
{
    protected $user_oneof;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type \User\V1\UserRes $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.user.v1.UserRes data = 3;</code>
     * @return \User\V1\UserRes
     */
    public function getData()
    {
        return $this->readOneof(3);
    }

    /**
     * Generated from protobuf field <code>.user.v1.UserRes data = 3;</code>
     * @param \User\V1\UserRes $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \User\V1\UserRes::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getUserOneof()
    {
        return $this->whichOneof("user_oneof");
    }

}

